### ISSUE TITLE
Hosted Heroku link not working

### ISSUE THREAD

**Issue by bikkimahato** [shravan20/github-readme-quotes#156]
Hosted Heroku link not working

**Screenshots**
![image](https://user-images.githubusercontent.com/42492682/139061114-cbfddecb-1ccd-42b4-ab9c-d73eefe242a5.png)

**Desktop:**
 - OS: [Windows]
 - Browser [chrome]

**Comment by abhijain2003** [comment]
have you uploaded database to server

**Comment by tanmayyb** [comment]
getting the same error today...

**Comment by abhijain2003** [comment]
heroku logs --tail --app your_app_name  run this command in git and check do you get any errors in deploy if yes then deploy it again with a correct manner

**Comment by tanmayyb** [comment]
hey abhi, I'm using the api for this repository in one of my readme.md's. how would I go about doing what you just told me in my case? Thanks in advance.

**Comment by abhijain2003** [comment]
that does not matter in you git cd to the root folder of your project and run the command to check logs of Heroku. if you find out error in logs. if you use any string in API which store in .env file then you need to add environment variables in heroku app also

**Comment by tanmayyb** [comment]
the api used to work in my private repository README's before, but this week due to some reason it suddenly stopped working. I don't think I have heroku installed on my end so this is what I get when I try to run 
`heroku logs --tail --cam_sys-22 `
(my repo is named cam_sys-22).
![image](https://user-images.githubusercontent.com/72982560/170796006-86b22c02-5175-4941-acd1-04ff51758185.png)

**Comment by abhijain2003** [comment]
go to youtube and watch a tutorial for this try deployment
 again from start

**Comment by shravan20** [comment]
Since we are using a free quota, every month we have a downtime of 1/1.5 day for which it won't be available.
I hope that clarifies system unavailability of the utility for some time every month

**Comment by mananbansal2002** [comment]
why not host it on some other provider then which is free? like netlify maybe
@shravan20

**Comment by shravan20** [comment]
Can anyone pick this up for deployment in any of the service of your own?

**Comment by ashishk1331** [comment]
Why not shift the code to render.com?

**Comment by shravan20** [comment]
> Why not shift the code to render.com?

This has been moved to GCP now, you can continue using it.

**Comment by ashishk1331** [comment]
That's the reason why your IP for the URL for the project. However, the site doesn't works on handheld devices.

Also, from the website to README file, the forwarding URL is mentioned of heroku. I think that needs a change.

![SmartSelect_20230927-185135_GitHub.jpg](https://github.com/shravan20/github-readme-quotes/assets/44055846/3f04c1bb-ae19-4980-97b1-f4ba3b9210f1)

**Comment by shravan20** [comment]
@ashishk1331 : I am able to access the website in mobile devices. Do you want to pick this issue up to update the documents with images instead of those URL so as to save unwanted API additional calls?
Or we can make it cacheable calls too, I think this is a better idea. Would you like to pick this up?

**Comment by ashishk1331** [comment]
Yes sir. I would love to pick it up.

Also, I'm a bit confused about replacing API calls with images. So, Instead of displaying API endpoint you want to display pre-saved images for the same?

I can update the API url to match the current url.

**Comment by shravan20** [comment]
@ashishk1331: 

This part of the code is responsible for not caching the response in the github content and dynamically generating new quotes that is shown on the github readme. This part of the code explicitly set response header to expire the reponse within 0 seconds even if it has been cached, forcing it to invalidated.

You can introduce a field to skip this caching and completely skip the below header being set. This would ensure github cache not being invalidated.

```
res.header(
        "Cache-Control",
        "no-cache,max-age=0,no-store,s-maxage=0,proxy-revalidate"
        );
     res.header("Pragma", "no-cache");
     res.header("Expires", "-1");
```

**Comment by ashishk1331** [comment]
I implemented public caching for 1 hour. However, time can be changed by modifying the hours variable before the header.
However, I think until and unless there is a change made by the user, we can cache the response for a year. Because README remains still for years.
![image](https://github.com/shravan20/github-readme-quotes/assets/44055846/8ffc76fd-6bd3-4b4a-990a-c9bb1ace1729)

**Comment by shravan20** [comment]
Let's keep it optional, only if you pass a value in query params

**Comment by ashishk1331** [comment]
Okay. So the query parameters namely cache and expire_after can do the trick,
```
cache = true | false
expire_after = 1 (hours)
```
Would generate the cache header with max age of 1 hour. 
Something like this?

**Comment by shravan20** [comment]
Folks we have moved it to vercel, closing this issue. Please do check the latest documentation changes.

**Comment by shravan20** [comment]
Marking this as closed as it is fixed, by migrating the application to vercel
